project:
  type: website
  output-dir: docs
  post-render:
    - ./fix-sitemap.sh

website:
  favicon: favicon.ico
  title: "Mastering Javascript"
  reader-mode: false
  open-graph: true
  twitter-card:
    site: "@krimuthu"
    card-style: summary
  google-analytics: 
    tracking-id: 'G-MDPY7CV76H'
  site-url: 'https://js.muthu.co'
  site-path: '/'
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/muthuspark
      - icon: twitter
        href: https://twitter.com/krimuthu
  comments: 
    utterances:
      repo: muthuspark/js-interview-questions
format:
  html:
    theme: litera
    css: styles.css
    lang: en
    toc: true
    image: false
    mermaid:
      theme: neutral
    filters:
      - canonical
    include-after-body:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3609399560636561" crossorigin="anonymous"></script>



